AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation Template to Deploy WordPress on EC2. Database is installed within the instance"

Parameters:
  KeyName:
    Description: "Name of an existing EC2 KeyPair to enable SSH access"
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  AvailabilityZone:
    Description: "Choose an Availability Zone"
    Type: AWS::EC2::AvailabilityZone::Name
  DomainName:
    Description: "Route53 Domain Name (e.g., example.com)"
    Type: String
  SubDomain:
    Description: "Subdomain to associate with the instance (e.g., www)"
    Type: String
    Default: "www"

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: WordPress-VPC

  # Internet Gateway
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Subnet
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: WordPress-Subnet

  # Route Table
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  MyRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet
      RouteTableId: !Ref MyRouteTable

  # Security Group
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP, HTTPS, and SSH access"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  WordPressInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316  # AMI de Amazon Linux 2 (usualmente en us-east-1)
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref MySubnet
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: WordPress-Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras enable php8.0
          sudo yum install -y php php-mysqlnd httpd mariadb-client wget mariadb-server

          systemctl start httpd
          systemctl enable httpd
          systemctl start mariadb
          systemctl enable mariadb

          # Establecer la contrase침a para el usuario root de MariaDB
          sudo mysql <<EOF
          ALTER USER 'root'@'localhost' IDENTIFIED BY 'nueva_contrase침a';
          FLUSH PRIVILEGES;
          EOF

          # Download WordPress
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cp -r wordpress/* .
          sudo rm -rf wordpress latest.tar.gz

          # Configurar .htaccess para redirecci칩n HTTPS
          echo '<IfModule mod_rewrite.c>' > /var/www/html/.htaccess
          echo '  RewriteEngine On' >> /var/www/html/.htaccess
          echo '  RewriteCond %{HTTPS} !=on' >> /var/www/html/.htaccess
          echo '  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]' >> /var/www/html/.htaccess
          echo '</IfModule>' >> /var/www/html/.htaccess

          # Create wp-config.php
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/wordpressdb/" wp-config.php
          sed -i "s/username_here/root/" wp-config.php
          sed -i "s/password_here/nueva_contrase침a/" wp-config.php

          sudo chown -R apache:apache /var/www/html
          sudo chmod -R 755 /var/www/html

          systemctl restart httpd

  # Elastic IP
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WordPressInstance

  # Route53 Record
  MyDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${SubDomain}.${DomainName}."
      Type: A
      TTL: '60'
      ResourceRecords:
        - !Ref MyElasticIP

Outputs:
  WebsiteURL:
    Description: "WordPress Website URL"
    Value: !Sub "http://${SubDomain}.${DomainName}"
